### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by aberel** [christian-vigh-phpclasses/SearchableFile#1]
Hi, I think this class would be very usefull to my needs.
I started trying preg_match.php, with a  25Mb csv file, and got this error:

**Fatal error: 
Uncaught exception 'RuntimeException' with message 'Invalid modifier 'o' in regular expression.' in SearchableFile.phpclass:941 
Stack trace: 
#0 SearchableFile.phpclass(724): SearchableFile->transform_regex('52442735-365670...')
#1 preg_match.php(18): SearchableFile->pcre_match('52442735-365670...', NULL, 256, 0)
#2 {main} thrown in SearchableFile.phpclass on line 941**

Then I found that,the fatal error changes the line, depending on the search string 
E.g. 
$re = "52442735-3656706299-816328" shows fatal error on line 941.
$re = "52442735" shows fatal error on line 732.

Any ideas? 
Thank you!

**Comment by christian-vigh-phpclasses** [comment]
Hello,

For the other readers, I updated the class here and on the http://www.phpclasses.org site.

Exchanges are available here :

http://www.phpclasses.org/discuss/package/9697/thread/1/

Christian.
